# If you are not sure what all these fields mean, please refer our documentation here:
# https://evalai.readthedocs.io/en/latest/configuration.html
title: Avalon Challenge
short_description: A 3D video game requiring generalization in reinforcement learning
description: templates/description.html
evaluation_details: templates/evaluation_details.html
terms_and_conditions: templates/terms_and_conditions.html
image: logo.jpg
submission_guidelines: templates/submission_guidelines.html
leaderboard_description:
evaluation_script: evaluation_script.zip # Not used
remote_evaluation: True
is_docker_based: True
start_date: 2022-01-01 00:00:00
end_date: 2099-05-31 23:59:59
published: True

leaderboard:
  - id: 1
    schema:
      {
        "labels": ["Total"],
        "default_order_by": "Total",
      }

challenge_phases:
  - id: 1
    name: Minival Phase
    description: templates/challenge_phase_minival_description.html
    leaderboard_public: False
    is_public: True
    is_submission_public: True
    start_date: 2022-01-01 00:00:00
    end_date: 2099-12-31 23:59:59
    codename: minival
    max_submissions_per_day: 100
    max_submissions_per_month: 3000
    max_submissions: 9999
    default_submission_meta_attributes:
      - name: method_name
        is_visible: True
      - name: method_description
        is_visible: True
      - name: project_url
        is_visible: True
      - name: publication_url
        is_visible: True
    is_restricted_to_select_one_submission: False
    is_partial_submission_evaluation_enabled: False

  - id: 2
    name: Public Test Phase
    description: templates/challenge_phase_public_test_description.html
    leaderboard_public: True
    is_public: True
    is_submission_public: True
    start_date: 2022-01-01 00:00:00
    end_date: 2099-12-31 23:59:59
    codename: public_test
    max_submissions_per_day: 10
    max_submissions_per_month: 300
    max_submissions: 999
    default_submission_meta_attributes:
      - name: method_name
        is_visible: True
      - name: method_description
        is_visible: True
      - name: project_url
        is_visible: True
      - name: publication_url
        is_visible: True
    is_restricted_to_select_one_submission: False
    is_partial_submission_evaluation_enabled: False

  - id: 3
    name: Private Test Phase
    description: templates/challenge_phase_private_test_description.html
    leaderboard_public: True
    is_public: True
    is_submission_public: True
    start_date: 2022-01-01 00:00:00
    end_date: 2099-12-31 23:59:59
    codename: private_test
    max_submissions_per_day: 5
    max_submissions_per_month: 5
    max_submissions: 5
    default_submission_meta_attributes:
      - name: method_name
        is_visible: True
      - name: method_description
        is_visible: True
      - name: project_url
        is_visible: True
      - name: publication_url
        is_visible: True
    is_restricted_to_select_one_submission: False
    is_partial_submission_evaluation_enabled: False

dataset_splits:
  - id: 1
    name: Default Split
    codename: default_split

challenge_phase_splits:
  - challenge_phase_id: 1
    leaderboard_id: 1
    dataset_split_id: 1
    visibility: 3
    leaderboard_decimal_precision: 3
    is_leaderboard_order_descending: True
  - challenge_phase_id: 2
    leaderboard_id: 1
    dataset_split_id: 1
    visibility: 3
    leaderboard_decimal_precision: 3
    is_leaderboard_order_descending: True
  - challenge_phase_id: 3
    leaderboard_id: 1
    dataset_split_id: 1
    visibility: 3
    leaderboard_decimal_precision: 3
    is_leaderboard_order_descending: True
